import { RateCardSource } from '../../types';

export const PROVIDER_SOURCES: Record<string, RateCardSource> = {
  copilot: {
    id: 'copilot',
    provider: 'GitHub',
    product: 'Copilot',
    sourceUrl: 'https://docs.github.com/copilot/reference/copilot-billing/models-and-pricing',
    sourceType: 'official_docs',
    billingKind: 'credit_metered',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
    notes: ['AI credits and model pricing are documented but can change with product updates.'],
  },
  cursor: {
    id: 'cursor',
    provider: 'Cursor',
    product: 'Cursor',
    sourceUrl: 'https://cursor.com/pricing',
    sourceType: 'official_html',
    billingKind: 'hybrid_subscription_usage',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
    notes: ['Dynamic pricing page. Manual review recommended.'],
  },
  claudeCode: {
    id: 'claude-code',
    provider: 'Anthropic',
    product: 'Claude Code',
    sourceUrl: 'https://claude.com/pricing',
    sourceType: 'official_html',
    billingKind: 'subscription_quota',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
    notes: ['Subscription tiers (Pro, Max 5x, Max 20x) include Claude Code; per-developer cost varies widely by model and codebase.'],
  },
  anthropicApi: {
    id: 'anthropic-api',
    provider: 'Anthropic',
    product: 'Anthropic API',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    sourceType: 'official_docs',
    billingKind: 'token_metered',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  codexPricing: {
    id: 'codex-pricing',
    provider: 'OpenAI',
    product: 'OpenAI Codex',
    sourceUrl: 'https://developers.openai.com/codex/pricing',
    sourceType: 'official_docs',
    billingKind: 'subscription_allowance',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  codexAuth: {
    id: 'codex-auth',
    provider: 'OpenAI',
    product: 'OpenAI Codex',
    sourceUrl: 'https://developers.openai.com/codex/auth',
    sourceType: 'official_docs',
    billingKind: 'token_metered',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  openaiApi: {
    id: 'openai-api',
    provider: 'OpenAI',
    product: 'OpenAI API',
    sourceUrl: 'https://openai.com/api/pricing/',
    sourceType: 'official_html',
    billingKind: 'token_metered',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  geminiCodeAssist: {
    id: 'gemini-code-assist',
    provider: 'Google',
    product: 'Gemini Code Assist',
    sourceUrl: 'https://codeassist.google/products/business',
    sourceType: 'official_html',
    billingKind: 'subscription_quota',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  geminiApi: {
    id: 'gemini-api',
    provider: 'Google',
    product: 'Gemini API',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    sourceType: 'official_docs',
    billingKind: 'token_metered',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  antigravity: {
    id: 'antigravity',
    provider: 'Google',
    product: 'Antigravity',
    sourceUrl: 'https://antigravity.google/pricing',
    sourceType: 'official_html',
    billingKind: 'subscription_allowance',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  windsurf: {
    id: 'windsurf',
    provider: 'Windsurf',
    product: 'Windsurf',
    sourceUrl: 'https://windsurf.com/pricing',
    sourceType: 'official_html',
    billingKind: 'hybrid_subscription_usage',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  jetbrainsAi: {
    id: 'jetbrains-ai',
    provider: 'JetBrains',
    product: 'JetBrains AI',
    sourceUrl: 'https://www.jetbrains.com/help/ai-assistant/licensing-and-subscriptions.html',
    sourceType: 'official_docs',
    billingKind: 'subscription_quota',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  opencodeProviders: {
    id: 'opencode-providers',
    provider: 'OpenCode',
    product: 'OpenCode',
    sourceUrl: 'https://opencode.ai/docs/providers/',
    sourceType: 'official_docs',
    billingKind: 'byok_wrapper',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  opencodeGo: {
    id: 'opencode-go',
    provider: 'OpenCode',
    product: 'OpenCode Go',
    sourceUrl: 'https://opencode.ai/go',
    sourceType: 'official_html',
    billingKind: 'subscription_allowance',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  opencodeZen: {
    id: 'opencode-zen',
    provider: 'OpenCode',
    product: 'OpenCode Zen',
    sourceUrl: 'https://opencode.ai/zen',
    sourceType: 'official_html',
    billingKind: 'router_payg',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  cline: {
    id: 'cline',
    provider: 'Cline',
    product: 'Cline',
    sourceUrl: 'https://cline.bot/pricing',
    sourceType: 'official_html',
    billingKind: 'byok_wrapper',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  rooCode: {
    id: 'roo-code',
    provider: 'Roo Code',
    product: 'Roo Code',
    sourceUrl: 'https://docs.roocode.com/getting-started/connecting-api-provider',
    sourceType: 'official_docs',
    billingKind: 'byok_wrapper',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  continuePricing: {
    id: 'continue-pricing',
    provider: 'Continue',
    product: 'Continue',
    sourceUrl: 'https://www.continue.dev/pricing',
    sourceType: 'official_html',
    billingKind: 'seat_license',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  continueProviders: {
    id: 'continue-model-providers',
    provider: 'Continue',
    product: 'Continue',
    sourceUrl: 'https://docs.continue.dev/customize/model-providers/overview',
    sourceType: 'official_docs',
    billingKind: 'byok_wrapper',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  kiloPricing: {
    id: 'kilo-pricing',
    provider: 'Kilo',
    product: 'Kilo',
    sourceUrl: 'https://kilo.ai/pricing',
    sourceType: 'official_html',
    billingKind: 'subscription_allowance',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  kiloDocs: {
    id: 'kilo-docs',
    provider: 'Kilo',
    product: 'Kilo',
    sourceUrl: 'https://kilo.ai/docs',
    sourceType: 'official_docs',
    billingKind: 'byok_wrapper',
    refreshStrategy: 'manual_review',
    confidence: 'high',
  },
  openrouterPricing: {
    id: 'openrouter-pricing',
    provider: 'OpenRouter',
    product: 'OpenRouter',
    sourceUrl: 'https://openrouter.ai/pricing',
    sourceType: 'official_html',
    billingKind: 'router_payg',
    refreshStrategy: 'manual_review',
    confidence: 'medium',
  },
  openrouterModels: {
    id: 'openrouter-models',
    provider: 'OpenRouter',
    product: 'OpenRouter',
    sourceUrl: 'https://openrouter.ai/docs/api-reference/list-available-models',
    sourceType: 'official_docs',
    billingKind: 'router_payg',
    refreshStrategy: 'json_api',
    confidence: 'medium',
    notes: ['Machine-readable endpoint can fail extraction from static fetchers.'],
  },
};