import { ProviderRateCard } from '../../types';
import { PROVIDER_SOURCES } from './sources';

export const SUBSCRIPTION_PROVIDER_RATE_CARDS: ProviderRateCard[] = [
  {
    schemaVersion: 1,
    productId: 'copilot-pro',
    provider: 'GitHub',
    product: 'GitHub Copilot',
    plan: 'Pro',
    billingKind: 'credit_metered',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 10, interval: 'monthly' },
    includedUsage: { unit: 'credits', amount: 1000, reset: 'monthly' },
    source: PROVIDER_SOURCES.copilot,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'copilot-pro-plus',
    provider: 'GitHub',
    product: 'GitHub Copilot',
    plan: 'Pro+',
    billingKind: 'credit_metered',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 39, interval: 'monthly' },
    includedUsage: { unit: 'credits', amount: 3900, reset: 'monthly' },
    source: PROVIDER_SOURCES.copilot,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'codex-go',
    provider: 'OpenAI',
    product: 'OpenAI Codex',
    plan: 'Go',
    billingKind: 'subscription_allowance',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 8, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'rolling', notes: ['Lightweight tier for occasional Codex coding tasks.'] },
    source: PROVIDER_SOURCES.codexPricing,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'codex-plus',
    provider: 'OpenAI',
    product: 'OpenAI Codex',
    plan: 'Plus',
    billingKind: 'subscription_allowance',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 20, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'rolling', notes: ['Model-dependent usage limits.'] },
    source: PROVIDER_SOURCES.codexPricing,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'codex-pro',
    provider: 'OpenAI',
    product: 'OpenAI Codex',
    plan: 'Pro',
    billingKind: 'subscription_allowance',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 100, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'rolling', notes: ['5x or 20x usage tiers vs Plus depending on plan variant.'] },
    source: PROVIDER_SOURCES.codexPricing,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'claude-code-pro',
    provider: 'Anthropic',
    product: 'Claude Code',
    plan: 'Pro',
    billingKind: 'subscription_allowance',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 20, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'rolling', notes: ['Claude Pro plan includes Claude Code at baseline usage; $17/mo with annual billing.'] },
    source: PROVIDER_SOURCES.claudeCode,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'claude-code-max-5x',
    provider: 'Anthropic',
    product: 'Claude Code',
    plan: 'Max 5x',
    billingKind: 'subscription_quota',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 100, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'rolling', notes: ['5x more usage than Pro; suitable for moderate Claude Code workloads.'] },
    source: PROVIDER_SOURCES.claudeCode,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'claude-code-max-20x',
    provider: 'Anthropic',
    product: 'Claude Code',
    plan: 'Max 20x',
    billingKind: 'subscription_quota',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 200, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'rolling', notes: ['20x more usage than Pro; for heavy Claude Code workloads (avg enterprise dev: $150-250/mo).'] },
    source: PROVIDER_SOURCES.claudeCode,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'cursor-pro',
    provider: 'Cursor',
    product: 'Cursor',
    plan: 'Pro',
    billingKind: 'hybrid_subscription_usage',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 20, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'monthly', notes: ['Includes model usage pool with possible overage.'] },
    overage: { enabled: true, unit: 'api_price', notes: ['On-demand usage can spill beyond included limits.'] },
    source: PROVIDER_SOURCES.cursor,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 7,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'cursor-pro-plus',
    provider: 'Cursor',
    product: 'Cursor',
    plan: 'Pro+',
    billingKind: 'hybrid_subscription_usage',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 60, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'monthly', notes: ['3x usage on all OpenAI, Claude, Gemini models vs Pro.'] },
    overage: { enabled: true, unit: 'api_price' },
    source: PROVIDER_SOURCES.cursor,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 7,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'cursor-ultra',
    provider: 'Cursor',
    product: 'Cursor',
    plan: 'Ultra',
    billingKind: 'hybrid_subscription_usage',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 200, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'monthly', notes: ['20x usage vs Pro on all OpenAI, Claude, Gemini models; priority access.'] },
    overage: { enabled: true, unit: 'api_price' },
    source: PROVIDER_SOURCES.cursor,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 7,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'cursor-teams',
    provider: 'Cursor',
    product: 'Cursor',
    plan: 'Teams',
    billingKind: 'seat_license',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 40, interval: 'monthly', perSeat: true },
    includedUsage: { unit: 'quota', reset: 'monthly', notes: ['Per-seat with centralized billing, analytics, RBAC, SSO.'] },
    overage: { enabled: true, unit: 'api_price' },
    source: PROVIDER_SOURCES.cursor,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 7,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'gemini-code-assist-standard',
    provider: 'Google',
    product: 'Gemini Code Assist',
    plan: 'Standard',
    billingKind: 'subscription_quota',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 22.8, interval: 'monthly', perSeat: true },
    includedUsage: { unit: 'requests', amount: 1500, reset: 'daily', notes: ['Developer program and console quotas vary by tier.'] },
    source: PROVIDER_SOURCES.geminiCodeAssist,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'gemini-code-assist-enterprise',
    provider: 'Google',
    product: 'Gemini Code Assist',
    plan: 'Enterprise',
    billingKind: 'seat_license',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 54, interval: 'monthly', perSeat: true },
    includedUsage: { unit: 'requests', amount: 2000, reset: 'daily' },
    source: PROVIDER_SOURCES.geminiCodeAssist,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'antigravity-individual',
    provider: 'Google',
    product: 'Antigravity',
    plan: 'Individual',
    billingKind: 'subscription_allowance',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 0, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'weekly', notes: ['Generous weekly limits without published token conversion.'] },
    source: PROVIDER_SOURCES.antigravity,
    confidence: 'medium',
    estimateKind: 'quota_pressure',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'antigravity-developer',
    provider: 'Google',
    product: 'Antigravity',
    plan: 'Developer via Google One',
    billingKind: 'subscription_allowance',
    credentialMode: 'account_login',
    currency: 'USD',
    includedUsage: { unit: 'quota', reset: 'weekly', notes: ['Uses Google AI Pro/Ultra subscription benefits and credit pool.'] },
    source: PROVIDER_SOURCES.antigravity,
    confidence: 'medium',
    estimateKind: 'quota_pressure',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'windsurf-pro',
    provider: 'Windsurf',
    product: 'Windsurf',
    plan: 'Pro',
    billingKind: 'hybrid_subscription_usage',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 20, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'weekly', notes: ['Includes usage allowance and supports API-priced extra usage.'] },
    overage: { enabled: true, unit: 'api_price' },
    source: PROVIDER_SOURCES.windsurf,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 7,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'windsurf-max',
    provider: 'Windsurf',
    product: 'Windsurf',
    plan: 'Max',
    billingKind: 'hybrid_subscription_usage',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 200, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'weekly', notes: ['Significantly higher quotas than Pro for heavy Cascade workloads.'] },
    overage: { enabled: true, unit: 'api_price' },
    source: PROVIDER_SOURCES.windsurf,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 7,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'windsurf-teams',
    provider: 'Windsurf',
    product: 'Windsurf',
    plan: 'Teams',
    billingKind: 'seat_license',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 40, interval: 'monthly', perSeat: true },
    includedUsage: { unit: 'quota', reset: 'weekly', notes: ['Per-seat with centralized billing, admin dashboard, priority support, zero data retention.'] },
    overage: { enabled: true, unit: 'api_price' },
    source: PROVIDER_SOURCES.windsurf,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 7,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'jetbrains-ai-pro',
    provider: 'JetBrains',
    product: 'JetBrains AI',
    plan: 'AI Pro',
    billingKind: 'subscription_quota',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 10, interval: 'monthly' },
    includedUsage: { unit: 'credits', amount: 10, reset: 'monthly' },
    creditRates: { creditUnitName: 'AI Credit', creditToUsd: 1 },
    source: PROVIDER_SOURCES.jetbrainsAi,
    confidence: 'medium',
    estimateKind: 'quota_pressure',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'jetbrains-ai-ultimate',
    provider: 'JetBrains',
    product: 'JetBrains AI',
    plan: 'AI Ultimate',
    billingKind: 'subscription_quota',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 30, interval: 'monthly' },
    includedUsage: { unit: 'credits', amount: 35, reset: 'monthly' },
    creditRates: { creditUnitName: 'AI Credit', creditToUsd: 1 },
    source: PROVIDER_SOURCES.jetbrainsAi,
    confidence: 'medium',
    estimateKind: 'quota_pressure',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'opencode-go',
    provider: 'OpenCode',
    product: 'OpenCode Go',
    plan: 'Go subscription',
    billingKind: 'subscription_allowance',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 10, interval: 'monthly' },
    includedUsage: { unit: 'quota', reset: 'rolling', notes: ['First month can be discounted; limits are plan-defined.'] },
    source: PROVIDER_SOURCES.opencodeGo,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'opencode-zen',
    provider: 'OpenCode',
    product: 'OpenCode Zen',
    plan: 'Pay as you go',
    billingKind: 'router_payg',
    credentialMode: 'router',
    currency: 'USD',
    includedUsage: { unit: 'dollars', amount: 20, reset: 'rolling', notes: ['Starts with prepaid balance and auto-top-up flow.'] },
    source: PROVIDER_SOURCES.opencodeZen,
    confidence: 'medium',
    estimateKind: 'range',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'continue-team',
    provider: 'Continue',
    product: 'Continue',
    plan: 'Team',
    billingKind: 'seat_license',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 20, interval: 'monthly', perSeat: true },
    includedUsage: { unit: 'dollars', amount: 10, reset: 'monthly', notes: ['Includes monthly model credits per seat.'] },
    source: PROVIDER_SOURCES.continuePricing,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
  {
    schemaVersion: 1,
    productId: 'kilo-pass-starter',
    provider: 'Kilo',
    product: 'Kilo Pass',
    plan: 'Starter',
    billingKind: 'subscription_allowance',
    credentialMode: 'account_login',
    currency: 'USD',
    subscription: { amount: 19, interval: 'monthly' },
    includedUsage: { unit: 'dollars', amount: 26.6, reset: 'monthly', notes: ['Published as up-to credit value and can depend on streak bonuses.'] },
    source: PROVIDER_SOURCES.kiloPricing,
    confidence: 'medium',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
  },
];