import { ProviderRateCard } from '../../types';
import { PROVIDER_SOURCES } from './sources';

export const TOKEN_METERED_PROVIDER_RATE_CARDS: ProviderRateCard[] = [
  {
    schemaVersion: 1,
    productId: 'openai-api-gpt-5.4',
    provider: 'OpenAI',
    product: 'OpenAI API',
    plan: 'GPT-5.4 reference',
    billingKind: 'token_metered',
    credentialMode: 'api_key',
    currency: 'USD',
    tokenRates: {
      inputPerMTok: 2.5,
      outputPerMTok: 15,
      cachedInputPerMTok: 0.25,
    },
    source: PROVIDER_SOURCES.openaiApi,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
  },
  {
    schemaVersion: 1,
    productId: 'openai-codex-api-key',
    provider: 'OpenAI',
    product: 'OpenAI Codex',
    plan: 'API key mode',
    billingKind: 'token_metered',
    credentialMode: 'api_key',
    currency: 'USD',
    tokenRates: {
      inputPerMTok: 1.75,
      outputPerMTok: 14,
      cachedInputPerMTok: 0.175,
    },
    source: PROVIDER_SOURCES.codexAuth,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: false,
    notes: ['Codex API-key mode uses standard API rates.'],
  },
  {
    schemaVersion: 1,
    productId: 'anthropic-api-claude-sonnet-4.6',
    provider: 'Anthropic',
    product: 'Anthropic API',
    plan: 'Claude Sonnet 4.6 reference',
    billingKind: 'token_metered',
    credentialMode: 'api_key',
    currency: 'USD',
    tokenRates: {
      inputPerMTok: 3,
      outputPerMTok: 15,
      cachedInputPerMTok: 0.3,
      cacheWritePerMTok: 3.75,
    },
    source: PROVIDER_SOURCES.anthropicApi,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
  },
  {
    schemaVersion: 1,
    productId: 'gemini-api-gemini-3.1-pro',
    provider: 'Google',
    product: 'Gemini API',
    plan: 'Gemini 3.1 Pro reference',
    billingKind: 'token_metered',
    credentialMode: 'api_key',
    currency: 'USD',
    tokenRates: {
      inputPerMTok: 2,
      outputPerMTok: 12,
      cachedInputPerMTok: 0.2,
    },
    source: PROVIDER_SOURCES.geminiApi,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
  },
  {
    schemaVersion: 1,
    productId: 'continue-starter-payg',
    provider: 'Continue',
    product: 'Continue',
    plan: 'Starter pay-as-you-go',
    billingKind: 'token_metered',
    credentialMode: 'account_login',
    currency: 'USD',
    tokenRates: {
      inputPerMTok: 3,
      outputPerMTok: 3,
    },
    source: PROVIDER_SOURCES.continuePricing,
    confidence: 'medium',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 14,
    requiresManualReview: true,
    notes: ['Published as combined token price; treated as symmetric input/output for estimator v1.'],
  },
  {
    schemaVersion: 1,
    productId: 'openrouter-payg',
    provider: 'OpenRouter',
    product: 'OpenRouter',
    plan: 'Pay as you go router',
    billingKind: 'router_payg',
    credentialMode: 'router',
    currency: 'USD',
    overage: {
      enabled: true,
      unit: 'token',
      notes: ['Model-dependent prices and platform fees apply.'],
    },
    source: PROVIDER_SOURCES.openrouterPricing,
    confidence: 'medium',
    estimateKind: 'range',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 7,
    requiresManualReview: true,
    notes: ['Prefer OpenRouter model list API for exact per-model pricing when available.'],
  },
];