import { ProviderRateCard } from '../../types';
import { PROVIDER_SOURCES } from './sources';

export const WRAPPER_PROVIDER_RATE_CARDS: ProviderRateCard[] = [
  {
    schemaVersion: 1,
    productId: 'opencode-byok',
    provider: 'OpenCode',
    product: 'OpenCode',
    plan: 'BYOK mode',
    billingKind: 'byok_wrapper',
    credentialMode: 'byok',
    currency: 'USD',
    source: PROVIDER_SOURCES.opencodeProviders,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
    notes: ['OpenCode wrapper delegates billing to the selected provider/model.'],
  },
  {
    schemaVersion: 1,
    productId: 'cline-byok',
    provider: 'Cline',
    product: 'Cline',
    plan: 'BYOK mode',
    billingKind: 'byok_wrapper',
    credentialMode: 'byok',
    currency: 'USD',
    source: PROVIDER_SOURCES.cline,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
    notes: ['Open-source wrapper; billing source is underlying provider.'],
  },
  {
    schemaVersion: 1,
    productId: 'roo-code-byok',
    provider: 'Roo Code',
    product: 'Roo Code',
    plan: 'BYOK mode',
    billingKind: 'byok_wrapper',
    credentialMode: 'byok',
    currency: 'USD',
    source: PROVIDER_SOURCES.rooCode,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
    notes: ['Router/account modes can differ; v1 assumes BYOK for exact delegation.'],
  },
  {
    schemaVersion: 1,
    productId: 'continue-byok',
    provider: 'Continue',
    product: 'Continue',
    plan: 'BYOK mode',
    billingKind: 'byok_wrapper',
    credentialMode: 'byok',
    currency: 'USD',
    source: PROVIDER_SOURCES.continueProviders,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
  },
  {
    schemaVersion: 1,
    productId: 'kilo-byok',
    provider: 'Kilo',
    product: 'Kilo',
    plan: 'BYOK mode',
    billingKind: 'byok_wrapper',
    credentialMode: 'byok',
    currency: 'USD',
    source: PROVIDER_SOURCES.kiloDocs,
    confidence: 'high',
    estimateKind: 'exact_formula',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
  },
  {
    schemaVersion: 1,
    productId: 'local-model-runner',
    provider: 'Local',
    product: 'Local model stack',
    plan: 'Ollama/LM Studio/llama.cpp',
    billingKind: 'local_model',
    credentialMode: 'local',
    currency: 'USD',
    source: PROVIDER_SOURCES.opencodeProviders,
    confidence: 'high',
    estimateKind: 'plan_fit',
    lastCheckedAt: '2026-05-06',
    staleAfterDays: 30,
    requiresManualReview: false,
    notes: ['Direct provider cost is usually 0. Hardware and energy costs are not estimated.'],
  },
];