/** Model pricing table based on GitHub Docs "Models and pricing for GitHub Copilot".
 *  All values in USD per 1,000,000 tokens. */

import { ModelPricing } from '../types';

export const MODEL_PRICING: Record<string, ModelPricing> = {
  // OpenAI
  'gpt-4.1': {
    id: 'gpt-4.1',
    displayName: 'GPT-4.1',
    provider: 'OpenAI',
    category: 'Versatile',
    releaseStatus: 'Retired',
    retiredDate: '2026-06-01',
    successorId: 'gpt-5.5',
    inputPerMillion: 2,
    cachedInputPerMillion: 0.5,
    outputPerMillion: 8,
    notes: ['Retired on 2026-06-01; succeeded by GPT-5.5.'],
  },
  'gpt-5-mini': {
    id: 'gpt-5-mini',
    displayName: 'GPT-5 mini',
    provider: 'OpenAI',
    category: 'Lightweight',
    releaseStatus: 'GA',
    inputPerMillion: 0.25,
    cachedInputPerMillion: 0.025,
    outputPerMillion: 2,
    notes: ['Included model in GitHub Copilot pricing table.'],
  },
  'gpt-5.2': {
    id: 'gpt-5.2',
    displayName: 'GPT-5.2',
    provider: 'OpenAI',
    category: 'Versatile',
    releaseStatus: 'Retired',
    retiredDate: '2026-06-01',
    successorId: 'gpt-5.5',
    inputPerMillion: 1.75,
    cachedInputPerMillion: 0.175,
    outputPerMillion: 14,
    notes: ['Retired on 2026-06-01; succeeded by GPT-5.5.'],
  },
  'gpt-5.2-codex': {
    id: 'gpt-5.2-codex',
    displayName: 'GPT-5.2-Codex',
    provider: 'OpenAI',
    category: 'Powerful',
    releaseStatus: 'Retired',
    retiredDate: '2026-06-01',
    successorId: 'gpt-5.3-codex',
    inputPerMillion: 1.75,
    cachedInputPerMillion: 0.175,
    outputPerMillion: 14,
    notes: ['Retired on 2026-06-01; succeeded by GPT-5.3-Codex.'],
  },
  'gpt-5.3-codex': {
    id: 'gpt-5.3-codex',
    displayName: 'GPT-5.3-Codex',
    provider: 'OpenAI',
    category: 'Powerful',
    releaseStatus: 'GA',
    inputPerMillion: 1.75,
    cachedInputPerMillion: 0.175,
    outputPerMillion: 14,
    notes: ['Good comparison baseline for coding-agent usage.'],
  },
  'gpt-5.4': {
    id: 'gpt-5.4',
    displayName: 'GPT-5.4',
    provider: 'OpenAI',
    category: 'Versatile',
    releaseStatus: 'GA',
    inputPerMillion: 2.5,
    cachedInputPerMillion: 0.25,
    outputPerMillion: 15,
    notes: ['Pricing applies to prompts with <=272K tokens.'],
  },
  'gpt-5.4-mini': {
    id: 'gpt-5.4-mini',
    displayName: 'GPT-5.4 mini',
    provider: 'OpenAI',
    category: 'Lightweight',
    releaseStatus: 'GA',
    inputPerMillion: 0.75,
    cachedInputPerMillion: 0.075,
    outputPerMillion: 4.5,
    notes: ['Lower-cost model for frequent usage.'],
  },
  'gpt-5.4-nano': {
    id: 'gpt-5.4-nano',
    displayName: 'GPT-5.4 nano',
    provider: 'OpenAI',
    category: 'Lightweight',
    releaseStatus: 'GA',
    inputPerMillion: 0.2,
    cachedInputPerMillion: 0.02,
    outputPerMillion: 1.25,
  },
  'gpt-5.5': {
    id: 'gpt-5.5',
    displayName: 'GPT-5.5',
    provider: 'OpenAI',
    category: 'Powerful',
    releaseStatus: 'GA',
    inputPerMillion: 5,
    cachedInputPerMillion: 0.5,
    outputPerMillion: 30,
  },

  // Anthropic
  'claude-haiku-4.5': {
    id: 'claude-haiku-4.5',
    displayName: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    category: 'Versatile',
    releaseStatus: 'GA',
    inputPerMillion: 1,
    cachedInputPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
    outputPerMillion: 5,
    notes: ['Anthropic models include cache write cost.'],
  },
  'claude-sonnet-4': {
    id: 'claude-sonnet-4',
    displayName: 'Claude Sonnet 4',
    provider: 'Anthropic',
    category: 'Versatile',
    releaseStatus: 'Retired',
    retiredDate: '2026-05-01',
    successorId: 'claude-sonnet-4.6',
    inputPerMillion: 3,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    outputPerMillion: 15,
    notes: ['Retired on 2026-05-01; succeeded by Claude Sonnet 4.6.'],
  },
  'claude-sonnet-4.5': {
    id: 'claude-sonnet-4.5',
    displayName: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    category: 'Versatile',
    releaseStatus: 'GA',
    inputPerMillion: 3,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    outputPerMillion: 15,
    notes: ['Anthropic models include cache write cost.'],
  },
  'claude-sonnet-4.6': {
    id: 'claude-sonnet-4.6',
    displayName: 'Claude Sonnet 4.6',
    provider: 'Anthropic',
    category: 'Versatile',
    releaseStatus: 'GA',
    inputPerMillion: 3,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    outputPerMillion: 15,
    notes: ['Anthropic models include cache write cost.'],
  },
  'claude-opus-4.7': {
    id: 'claude-opus-4.7',
    displayName: 'Claude Opus 4.7',
    provider: 'Anthropic',
    category: 'Powerful',
    releaseStatus: 'GA',
    inputPerMillion: 5,
    cachedInputPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    outputPerMillion: 25,
    notes: ['Higher-cost model for deeper reasoning.'],
  },
  'claude-opus-4.5': {
    id: 'claude-opus-4.5',
    displayName: 'Claude Opus 4.5',
    provider: 'Anthropic',
    category: 'Powerful',
    releaseStatus: 'GA',
    inputPerMillion: 5,
    cachedInputPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    outputPerMillion: 25,
    notes: ['Anthropic models include cache write cost.'],
  },
  'claude-opus-4.6': {
    id: 'claude-opus-4.6',
    displayName: 'Claude Opus 4.6',
    provider: 'Anthropic',
    category: 'Powerful',
    releaseStatus: 'GA',
    inputPerMillion: 5,
    cachedInputPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    outputPerMillion: 25,
    notes: ['Anthropic models include cache write cost.'],
  },
  'claude-opus-4.8': {
    id: 'claude-opus-4.8',
    displayName: 'Claude Opus 4.8',
    provider: 'Anthropic',
    category: 'Powerful',
    releaseStatus: 'GA',
    inputPerMillion: 5,
    cachedInputPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    outputPerMillion: 25,
    notes: ['Anthropic models include cache write cost.'],
  },
  'claude-opus-4.8-fast': {
    id: 'claude-opus-4.8-fast',
    displayName: 'Claude Opus 4.8 (fast)',
    provider: 'Anthropic',
    category: 'Powerful',
    releaseStatus: 'Public preview',
    inputPerMillion: 10,
    cachedInputPerMillion: 1,
    cacheWritePerMillion: 12.5,
    outputPerMillion: 50,
    notes: ['Fast-tier variant priced at 2x standard Opus.'],
  },
  'claude-fable-5': {
    id: 'claude-fable-5',
    displayName: 'Claude Fable 5',
    provider: 'Anthropic',
    category: 'Powerful',
    releaseStatus: 'GA',
    inputPerMillion: 10,
    cachedInputPerMillion: 1,
    cacheWritePerMillion: 12.5,
    outputPerMillion: 50,
    notes: ['Anthropic models include cache write cost.'],
  },

  // Google
  'gemini-2.5-pro': {
    id: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    provider: 'Google',
    category: 'Powerful',
    releaseStatus: 'GA',
    inputPerMillion: 1.25,
    cachedInputPerMillion: 0.125,
    outputPerMillion: 10,
    notes: ['Pricing applies to prompts with <=200K tokens.'],
  },
  'gemini-3-flash': {
    id: 'gemini-3-flash',
    displayName: 'Gemini 3 Flash',
    provider: 'Google',
    category: 'Lightweight',
    releaseStatus: 'Public preview',
    inputPerMillion: 0.5,
    cachedInputPerMillion: 0.05,
    outputPerMillion: 3,
    notes: ['No long-context surcharge.'],
  },
  'gemini-3.1-pro': {
    id: 'gemini-3.1-pro',
    displayName: 'Gemini 3.1 Pro',
    provider: 'Google',
    category: 'Powerful',
    releaseStatus: 'Public preview',
    inputPerMillion: 2,
    cachedInputPerMillion: 0.2,
    outputPerMillion: 12,
    notes: ['Pricing applies to prompts with <=200K tokens.'],
  },
  'gemini-3.5-flash': {
    id: 'gemini-3.5-flash',
    displayName: 'Gemini 3.5 Flash',
    provider: 'Google',
    category: 'Lightweight',
    releaseStatus: 'GA',
    inputPerMillion: 1.5,
    cachedInputPerMillion: 0.15,
    outputPerMillion: 9,
    notes: ['No long-context surcharge.'],
  },

  // xAI
  'grok-code-fast-1': {
    id: 'grok-code-fast-1',
    displayName: 'Grok Code Fast 1',
    provider: 'xAI',
    category: 'Lightweight',
    releaseStatus: 'Retired',
    retiredDate: '2026-05-15',
    successorId: 'gpt-5-mini',
    inputPerMillion: 0.2,
    cachedInputPerMillion: 0.02,
    outputPerMillion: 1.5,
    notes: ['Retired on 2026-05-15; succeeded by GPT-5 mini.'],
  },

  // Microsoft
  'mai-code-1-flash': {
    id: 'mai-code-1-flash',
    displayName: 'MAI Code 1 Flash',
    provider: 'Microsoft',
    category: 'Lightweight',
    releaseStatus: 'GA',
    inputPerMillion: 0.75,
    cachedInputPerMillion: 0.075,
    outputPerMillion: 4.5,
    notes: ['Low-cost Microsoft coding model.'],
  },

  // Fine-tuned (GitHub)
  'raptor-mini': {
    id: 'raptor-mini',
    displayName: 'Raptor mini',
    provider: 'GitHub',
    category: 'Versatile',
    releaseStatus: 'GA',
    inputPerMillion: 0.25,
    cachedInputPerMillion: 0.025,
    outputPerMillion: 2,
    notes: ['Uses GPT-5 mini pricing.'],
  },
  goldeneye: {
    id: 'goldeneye',
    displayName: 'Goldeneye',
    provider: 'GitHub',
    category: 'Powerful',
    releaseStatus: 'Retired',
    retiredDate: '2026-06-01',
    inputPerMillion: 1.25,
    cachedInputPerMillion: 0.125,
    outputPerMillion: 10,
    notes: ['Internal codename; retired/evaluation model.'],
  },
};

/** Convenience array, ordered for UI display (active first cheap → expensive, retired last). */
export const MODEL_PRICING_LIST: ModelPricing[] = Object.values(MODEL_PRICING)
  .slice()
  .sort((a, b) => {
    const aRetired = a.releaseStatus === 'Retired' ? 1 : 0;
    const bRetired = b.releaseStatus === 'Retired' ? 1 : 0;
    if (aRetired !== bRetired) {
      return aRetired - bRetired;
    }
    return a.outputPerMillion - b.outputPerMillion;
  });
